add build.sh and run.sh
ACLoong/nba-tall pull request #13
Opened 2018-06-27 17:00 UTC by MrKingHH

I have added the build.sh and run.sh. If uyou are free, can you help me to review these code?
@wangqing1218 @zmzhouXJTU

2018-06-28 15:37 UTC, zmzhouXJTU commented
sorry，I have seen it just now . I will review the code as soon as possible

2018-06-29 15:16 UTC, wangqing1218 commented
I have not receive the review request.
I will review it right now.
By the way, I advice you to set the reviewers for next PR.

2018-07-01 11:57 UTC, wangqing1218 requested changes

2018-07-01 11:57 UTC, wangqing1218 commented on SS/nbanews/build.sh
> +sudo apt install python3-pip
Maybe we should judge wether  it have installed yet on this machine, like this:
```shell
python = $(which python)
if [python=='python' or python=='python3'] then
    echo "python have installed."
else
   sudo apt install python
fi
```

2018-07-01 11:57 UTC, wangqing1218 commented on SS/nbanews/run.sh
> +rm *.txt
I think it's a bad idea to remove all files which are end of  the `.txt` postfix. 
We can write the '.txt' files in `xxx/build` folder that represent what the program output.
Then, our script can be written:
```shell
rm xxx/build/*.txt
```

2018-07-10 15:23 UTC, closed without merging